use super::{
    SqliteStore, SqliteStoreError, canonical_utc_timestamp_millis_v1, is_valid_reference_v1,
    verify_current_schema,
};
use crate::phase7_persistence::{
    Phase7AuthorizationAttemptRecordV1, Phase7PersistenceErrorV1, audit_binding_exists, blob_32,
    bounded_reference, digest_fields, phase7_entity_exists, read_validated_attempt_by_id,
    valid_prefixed_id,
};
use core::fmt;
use rusqlite::{Connection, OptionalExtension, Transaction, TransactionBehavior, params};
use sha2::{Digest, Sha256};
use std::time::{Duration, SystemTime, UNIX_EPOCH};
use zeroize::{Zeroize, Zeroizing};

/// Exact raw nonce size generated by server OS CSPRNG.
pub const PHASE7_NONCE_BYTES_V1: usize = 32;
/// Hard nonce lifetime cap. Approval expiry may shorten this window.
pub const PHASE7_NONCE_TTL_SECONDS_V1: u64 = 300;

const PHASE7_NONCE_TTL_MILLIS_V1: u64 = PHASE7_NONCE_TTL_SECONDS_V1 * 1_000;
const NONCE_ID_DOMAIN: &str = "lnsat.phase7.authorization-nonce-id.v1";
const NONCE_AUDIT_ID_DOMAIN: &str = "lnsat.phase7.authorization-nonce-audit-id.v1";
const NONCE_RECORD_DIGEST_DOMAIN: &str = "lnsat.phase7.authorization-nonce-record.v1";
const NONCE_STATE_EVENT_ID_DOMAIN: &str = "lnsat.phase7.nonce-state-event-id.v1";
const NONCE_STATE_AUDIT_ID_DOMAIN: &str = "lnsat.phase7.nonce-state-audit-id.v1";
const NONCE_STATE_DIGEST_DOMAIN: &str = "lnsat.phase7.nonce-state.v1";
const NONCE_STATE_RECORD_DIGEST_DOMAIN: &str = "lnsat.phase7.nonce-state-record.v1";
const LOWER_HEX: &[u8; 16] = b"0123456789abcdef";

/// Exact source scope for server-owned nonce issuance.
///
/// Callers provide no nonce, identifier, timestamp, or expiry.
#[derive(Clone, Copy, Debug)]
pub struct Phase7AuthorizationNonceIssueInputV1<'a> {
    pub project_ref: &'a str,
    pub resource_ref: &'a str,
    pub authorization_attempt_id: &'a str,
}

/// Exact source scope for server-owned nonce cancellation.
#[derive(Clone, Copy, Debug)]
pub struct Phase7AuthorizationNonceCancelInputV1<'a> {
    pub project_ref: &'a str,
    pub resource_ref: &'a str,
    pub nonce_id: &'a str,
}

/// Raw server nonce returned only for first successful issuance.
///
/// Persistence, audit, replay reads, and debug output never expose these bytes.
pub struct Phase7AuthorizationNonceSecretV1 {
    bytes: [u8; PHASE7_NONCE_BYTES_V1],
}

impl Phase7AuthorizationNonceSecretV1 {
    /// Borrows raw nonce bytes for immediate in-process handoff.
    #[must_use]
    pub const fn as_bytes(&self) -> &[u8; PHASE7_NONCE_BYTES_V1] {
        &self.bytes
    }
}

impl fmt::Debug for Phase7AuthorizationNonceSecretV1 {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str("Phase7AuthorizationNonceSecretV1(<redacted>)")
    }
}

impl Drop for Phase7AuthorizationNonceSecretV1 {
    fn drop(&mut self) {
        self.bytes.zeroize();
    }
}

/// Immutable digest-only nonce evidence plus latest terminal-safe state.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Phase7AuthorizationNonceRecordV1 {
    pub nonce_id: String,
    pub audit_binding_id: String,
    pub project_ref: String,
    pub resource_ref: String,
    pub authorization_attempt_id: String,
    pub binding_digest: [u8; 32],
    pub nonce_digest: [u8; 32],
    pub issued_at: String,
    pub expires_at: String,
    pub state_event_id: String,
    pub state_audit_binding_id: String,
    pub state_sequence: u32,
    pub state: String,
    pub state_effective_at: String,
    pub active: bool,
}

/// First issuance returns raw nonce once. Replay returns digest-only evidence.
#[derive(Debug)]
pub struct Phase7AuthorizationNonceIssueV1 {
    pub created: bool,
    pub nonce: Option<Phase7AuthorizationNonceSecretV1>,
    pub record: Phase7AuthorizationNonceRecordV1,
}

/// Result from cancellation or lazy terminal expiry materialization.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Phase7AuthorizationNonceTransitionV1 {
    pub changed: bool,
    pub record: Phase7AuthorizationNonceRecordV1,
}

#[derive(Clone, Debug)]
struct StoredNonce {
    nonce_id: String,
    audit_binding_id: String,
    project_ref: String,
    resource_ref: String,
    authorization_attempt_id: String,
    binding_digest: [u8; 32],
    nonce_digest: [u8; 32],
    issued_at: String,
    expires_at: String,
    stored_record_digest: [u8; 32],
    entity_created_at: String,
    audit_event_kind: String,
    audit_authority_effect: String,
    audit_recorded_at: String,
    events: Vec<StoredNonceStateEvent>,
}

#[derive(Clone, Debug)]
struct StoredNonceStateEvent {
    state_event_id: String,
    audit_binding_id: String,
    project_ref: String,
    resource_ref: String,
    target_entity_id: String,
    target_entity_kind: String,
    state_sequence: i64,
    state: String,
    prior_state_event_id: Option<String>,
    prior_state_sequence: Option<i64>,
    effective_at: String,
    state_digest: [u8; 32],
    stored_record_digest: [u8; 32],
    entity_created_at: String,
    audit_event_kind: String,
    audit_authority_effect: String,
    audit_recorded_at: String,
}

impl SqliteStore {
    /// Issues one server-owned nonce from OS CSPRNG and persists only its
    /// SHA-256 digest. Exact replay never re-exposes raw bytes.
    ///
    /// # Errors
    ///
    /// Fails closed for invalid scope, unavailable entropy, expired or drifted
    /// approval evidence, identifier collision, clock rejection, or atomic
    /// persistence failure.
    pub fn issue_phase7_authorization_nonce_v1(
        &mut self,
        input: &Phase7AuthorizationNonceIssueInputV1<'_>,
    ) -> Result<Phase7AuthorizationNonceIssueV1, Phase7PersistenceErrorV1> {
        let issued_time = SystemTime::now();
        let ttl_time = issued_time
            .checked_add(Duration::from_secs(PHASE7_NONCE_TTL_SECONDS_V1))
            .ok_or(Phase7PersistenceErrorV1::ClockRejected)?;
        let issued_at = canonical_system_time_v1(issued_time)?;
        let ttl_expires_at = canonical_system_time_v1(ttl_time)?;
        self.issue_phase7_authorization_nonce_from_sources_v1(
            input,
            &issued_at,
            &ttl_expires_at,
            |bytes| {
                getrandom::getrandom(bytes)
                    .map_err(|_| Phase7PersistenceErrorV1::EntropyUnavailable)
            },
            || Ok(()),
        )
    }

    #[cfg(test)]
    pub(super) fn issue_phase7_authorization_nonce_with_sources_v1<F, P>(
        &mut self,
        input: &Phase7AuthorizationNonceIssueInputV1<'_>,
        issued_at: &str,
        ttl_expires_at: &str,
        fill_entropy: F,
        precommit: P,
    ) -> Result<Phase7AuthorizationNonceIssueV1, Phase7PersistenceErrorV1>
    where
        F: FnOnce(&mut [u8; PHASE7_NONCE_BYTES_V1]) -> Result<(), Phase7PersistenceErrorV1>,
        P: FnOnce() -> Result<(), Phase7PersistenceErrorV1>,
    {
        self.issue_phase7_authorization_nonce_from_sources_v1(
            input,
            issued_at,
            ttl_expires_at,
            fill_entropy,
            precommit,
        )
    }

    #[allow(clippy::too_many_lines)] // Keep issue transaction and secret lifetime in one auditable scope.
    fn issue_phase7_authorization_nonce_from_sources_v1<F, P>(
        &mut self,
        input: &Phase7AuthorizationNonceIssueInputV1<'_>,
        issued_at: &str,
        ttl_expires_at: &str,
        fill_entropy: F,
        precommit: P,
    ) -> Result<Phase7AuthorizationNonceIssueV1, Phase7PersistenceErrorV1>
    where
        F: FnOnce(&mut [u8; PHASE7_NONCE_BYTES_V1]) -> Result<(), Phase7PersistenceErrorV1>,
        P: FnOnce() -> Result<(), Phase7PersistenceErrorV1>,
    {
        validate_issue_input(input)?;
        validate_ttl_window(issued_at, ttl_expires_at)?;
        let transaction = self
            .connection
            .transaction_with_behavior(TransactionBehavior::Immediate)
            .map_err(|_| Phase7PersistenceErrorV1::PersistenceFailed)?;
        verify_current_schema(&transaction).map_err(|_| Phase7PersistenceErrorV1::EvidenceDrift)?;
        let attempt = read_validated_attempt_by_id(
            &transaction,
            input.project_ref,
            input.resource_ref,
            input.authorization_attempt_id,
        )?
        .ok_or(Phase7PersistenceErrorV1::SourceNotApproved)?;

        if let Some(existing) = select_nonce_by_attempt(
            &transaction,
            input.project_ref,
            input.resource_ref,
            input.authorization_attempt_id,
        )? {
            let validated = validate_stored_nonce(&transaction, existing)?;
            let (validated, _) = materialize_expiry_if_needed(&transaction, validated, issued_at)?;
            let record = nonce_public_record(&validated, issued_at)?;
            precommit()?;
            transaction
                .commit()
                .map_err(|_| Phase7PersistenceErrorV1::PersistenceFailed)?;
            return Ok(Phase7AuthorizationNonceIssueV1 {
                created: false,
                nonce: None,
                record,
            });
        }

        let issued_millis = canonical_utc_timestamp_millis_v1(issued_at)
            .ok_or(Phase7PersistenceErrorV1::ClockRejected)?;
        let requested_millis = canonical_utc_timestamp_millis_v1(&attempt.requested_at)
            .ok_or(Phase7PersistenceErrorV1::EvidenceDrift)?;
        let attempt_expires_millis = canonical_utc_timestamp_millis_v1(&attempt.expires_at)
            .ok_or(Phase7PersistenceErrorV1::EvidenceDrift)?;
        if issued_millis < requested_millis || issued_millis >= attempt_expires_millis {
            return Err(Phase7PersistenceErrorV1::SourceNotApproved);
        }
        let ttl_expires_millis = canonical_utc_timestamp_millis_v1(ttl_expires_at)
            .ok_or(Phase7PersistenceErrorV1::ClockRejected)?;
        let expires_at = if ttl_expires_millis < attempt_expires_millis {
            ttl_expires_at.to_owned()
        } else {
            attempt.expires_at.clone()
        };

        let mut raw_nonce = Zeroizing::new([0_u8; PHASE7_NONCE_BYTES_V1]);
        fill_entropy(&mut raw_nonce)?;
        let nonce_digest: [u8; 32] = Sha256::digest(raw_nonce.as_slice()).into();
        if nonce_digest_exists(&transaction, input.project_ref, &nonce_digest)? {
            return Err(Phase7PersistenceErrorV1::IdentityConflict);
        }
        let nonce_id = identifier("non_", NONCE_ID_DOMAIN, &[nonce_digest.as_slice()]);
        let audit_binding_id = identifier("p7a_", NONCE_AUDIT_ID_DOMAIN, &[nonce_id.as_bytes()]);
        let base = StoredNonce {
            nonce_id,
            audit_binding_id,
            project_ref: input.project_ref.to_owned(),
            resource_ref: input.resource_ref.to_owned(),
            authorization_attempt_id: input.authorization_attempt_id.to_owned(),
            binding_digest: attempt.binding_digest,
            nonce_digest,
            issued_at: issued_at.to_owned(),
            expires_at,
            stored_record_digest: [0; 32],
            entity_created_at: issued_at.to_owned(),
            audit_event_kind: "nonce_state_recorded".to_owned(),
            audit_authority_effect: "none".to_owned(),
            audit_recorded_at: issued_at.to_owned(),
            events: Vec::new(),
        };
        let base_record_digest = nonce_record_digest(&base);
        if phase7_entity_exists(&transaction, &base.nonce_id)?
            || audit_binding_exists(&transaction, &base.audit_binding_id)?
        {
            return Err(Phase7PersistenceErrorV1::IdentityConflict);
        }
        insert_entity_and_audit(
            &transaction,
            &base.nonce_id,
            "authorization_nonce",
            &base.project_ref,
            &base.resource_ref,
            &base.audit_binding_id,
            &base_record_digest,
            "nonce_state_recorded",
            "none",
            &base.issued_at,
        )?;
        transaction
            .execute(
                "INSERT INTO lnsat_authorization_nonces (
                    nonce_id, entity_kind, project_ref, resource_ref,
                    authorization_attempt_id, binding_digest, nonce_digest,
                    issued_at, expires_at
                 ) VALUES (
                    ?1, 'authorization_nonce', ?2, ?3, ?4, ?5, ?6, ?7, ?8
                 )",
                params![
                    &base.nonce_id,
                    &base.project_ref,
                    &base.resource_ref,
                    &base.authorization_attempt_id,
                    base.binding_digest.as_slice(),
                    base.nonce_digest.as_slice(),
                    &base.issued_at,
                    &base.expires_at,
                ],
            )
            .map_err(|_| Phase7PersistenceErrorV1::PersistenceFailed)?;
        insert_nonce_state_event(&transaction, &base, "active", &base.issued_at, None)?;

        let stored = select_nonce_by_id(
            &transaction,
            &base.project_ref,
            &base.resource_ref,
            &base.nonce_id,
        )?
        .ok_or(Phase7PersistenceErrorV1::EvidenceDrift)?;
        let validated = validate_stored_nonce(&transaction, stored)?;
        let record = nonce_public_record(&validated, issued_at)?;
        if !record.active || record.state != "active" {
            return Err(Phase7PersistenceErrorV1::EvidenceDrift);
        }
        precommit()?;
        transaction
            .commit()
            .map_err(|_| Phase7PersistenceErrorV1::PersistenceFailed)?;
        let secret = Phase7AuthorizationNonceSecretV1 { bytes: *raw_nonce };
        raw_nonce.zeroize();
        Ok(Phase7AuthorizationNonceIssueV1 {
            created: true,
            nonce: Some(secret),
            record,
        })
    }

    /// Reads one exact nonce through server clock, lazily persisting terminal
    /// expiry when boundary has passed.
    ///
    /// # Errors
    ///
    /// Fails closed for invalid scope, clock rollback, evidence drift, or
    /// atomic persistence failure.
    pub fn read_phase7_authorization_nonce_v1(
        &mut self,
        project_ref: &str,
        resource_ref: &str,
        nonce_id: &str,
    ) -> Result<Option<Phase7AuthorizationNonceRecordV1>, Phase7PersistenceErrorV1> {
        let checked_at = canonical_system_time_v1(SystemTime::now())?;
        self.read_phase7_authorization_nonce_at_internal_v1(
            project_ref,
            resource_ref,
            nonce_id,
            &checked_at,
            || Ok(()),
        )
    }

    #[cfg(test)]
    pub(super) fn read_phase7_authorization_nonce_at_v1<P>(
        &mut self,
        project_ref: &str,
        resource_ref: &str,
        nonce_id: &str,
        checked_at: &str,
        precommit: P,
    ) -> Result<Option<Phase7AuthorizationNonceRecordV1>, Phase7PersistenceErrorV1>
    where
        P: FnOnce() -> Result<(), Phase7PersistenceErrorV1>,
    {
        self.read_phase7_authorization_nonce_at_internal_v1(
            project_ref,
            resource_ref,
            nonce_id,
            checked_at,
            precommit,
        )
    }

    fn read_phase7_authorization_nonce_at_internal_v1<P>(
        &mut self,
        project_ref: &str,
        resource_ref: &str,
        nonce_id: &str,
        checked_at: &str,
        precommit: P,
    ) -> Result<Option<Phase7AuthorizationNonceRecordV1>, Phase7PersistenceErrorV1>
    where
        P: FnOnce() -> Result<(), Phase7PersistenceErrorV1>,
    {
        validate_nonce_scope(project_ref, resource_ref, nonce_id)?;
        canonical_utc_timestamp_millis_v1(checked_at)
            .ok_or(Phase7PersistenceErrorV1::ClockRejected)?;
        let transaction = self
            .connection
            .transaction_with_behavior(TransactionBehavior::Immediate)
            .map_err(|_| Phase7PersistenceErrorV1::PersistenceFailed)?;
        verify_current_schema(&transaction).map_err(|_| Phase7PersistenceErrorV1::EvidenceDrift)?;
        let Some(stored) = select_nonce_by_id(&transaction, project_ref, resource_ref, nonce_id)?
        else {
            transaction
                .commit()
                .map_err(|_| Phase7PersistenceErrorV1::PersistenceFailed)?;
            return Ok(None);
        };
        let validated = validate_stored_nonce(&transaction, stored)?;
        let (validated, _) = materialize_expiry_if_needed(&transaction, validated, checked_at)?;
        let record = nonce_public_record(&validated, checked_at)?;
        precommit()?;
        transaction
            .commit()
            .map_err(|_| Phase7PersistenceErrorV1::PersistenceFailed)?;
        Ok(Some(record))
    }

    /// Cancels one exact active nonce. Expiry wins at exact expiry boundary;
    /// terminal states remain idempotent and cannot reactivate.
    ///
    /// # Errors
    ///
    /// Fails closed for invalid scope, clock rollback, evidence drift, or
    /// atomic persistence failure.
    pub fn cancel_phase7_authorization_nonce_v1(
        &mut self,
        input: &Phase7AuthorizationNonceCancelInputV1<'_>,
    ) -> Result<Option<Phase7AuthorizationNonceTransitionV1>, Phase7PersistenceErrorV1> {
        let cancelled_at = canonical_system_time_v1(SystemTime::now())?;
        self.cancel_phase7_authorization_nonce_at_internal_v1(input, &cancelled_at, || Ok(()))
    }

    #[cfg(test)]
    pub(super) fn cancel_phase7_authorization_nonce_at_v1<P>(
        &mut self,
        input: &Phase7AuthorizationNonceCancelInputV1<'_>,
        cancelled_at: &str,
        precommit: P,
    ) -> Result<Option<Phase7AuthorizationNonceTransitionV1>, Phase7PersistenceErrorV1>
    where
        P: FnOnce() -> Result<(), Phase7PersistenceErrorV1>,
    {
        self.cancel_phase7_authorization_nonce_at_internal_v1(input, cancelled_at, precommit)
    }

    fn cancel_phase7_authorization_nonce_at_internal_v1<P>(
        &mut self,
        input: &Phase7AuthorizationNonceCancelInputV1<'_>,
        cancelled_at: &str,
        precommit: P,
    ) -> Result<Option<Phase7AuthorizationNonceTransitionV1>, Phase7PersistenceErrorV1>
    where
        P: FnOnce() -> Result<(), Phase7PersistenceErrorV1>,
    {
        validate_nonce_scope(input.project_ref, input.resource_ref, input.nonce_id)?;
        let cancelled_millis = canonical_utc_timestamp_millis_v1(cancelled_at)
            .ok_or(Phase7PersistenceErrorV1::ClockRejected)?;
        let transaction = self
            .connection
            .transaction_with_behavior(TransactionBehavior::Immediate)
            .map_err(|_| Phase7PersistenceErrorV1::PersistenceFailed)?;
        verify_current_schema(&transaction).map_err(|_| Phase7PersistenceErrorV1::EvidenceDrift)?;
        let Some(stored) = select_nonce_by_id(
            &transaction,
            input.project_ref,
            input.resource_ref,
            input.nonce_id,
        )?
        else {
            transaction
                .commit()
                .map_err(|_| Phase7PersistenceErrorV1::PersistenceFailed)?;
            return Ok(None);
        };
        let validated = validate_stored_nonce(&transaction, stored)?;
        let issued_millis = canonical_utc_timestamp_millis_v1(&validated.issued_at)
            .ok_or(Phase7PersistenceErrorV1::EvidenceDrift)?;
        let latest_millis = canonical_utc_timestamp_millis_v1(
            &validated
                .events
                .last()
                .ok_or(Phase7PersistenceErrorV1::EvidenceDrift)?
                .effective_at,
        )
        .ok_or(Phase7PersistenceErrorV1::EvidenceDrift)?;
        if cancelled_millis < issued_millis || cancelled_millis < latest_millis {
            return Err(Phase7PersistenceErrorV1::ClockRejected);
        }
        let (validated, expired) =
            materialize_expiry_if_needed(&transaction, validated, cancelled_at)?;
        let mut changed = expired;
        let latest = validated
            .events
            .last()
            .ok_or(Phase7PersistenceErrorV1::EvidenceDrift)?;
        let validated = if latest.state == "active" {
            insert_nonce_state_event(
                &transaction,
                &validated,
                "cancelled",
                cancelled_at,
                Some(latest),
            )?;
            changed = true;
            let reloaded = select_nonce_by_id(
                &transaction,
                input.project_ref,
                input.resource_ref,
                input.nonce_id,
            )?
            .ok_or(Phase7PersistenceErrorV1::EvidenceDrift)?;
            validate_stored_nonce(&transaction, reloaded)?
        } else {
            validated
        };
        let record = nonce_public_record(&validated, cancelled_at)?;
        precommit()?;
        transaction
            .commit()
            .map_err(|_| Phase7PersistenceErrorV1::PersistenceFailed)?;
        Ok(Some(Phase7AuthorizationNonceTransitionV1 {
            changed,
            record,
        }))
    }
}

pub(super) fn verify_phase7_nonce_records_v1(
    connection: &Connection,
) -> Result<(), SqliteStoreError> {
    let state_event_count = connection
        .query_row(
            "SELECT count(*) FROM lnsat_phase7_state_events
             WHERE target_entity_kind = 'authorization_nonce'",
            [],
            |row| row.get::<_, i64>(0),
        )
        .map_err(|_| SqliteStoreError::MigrationDrift)?;
    let mut statement = connection
        .prepare(
            "SELECT nonce_id, project_ref, resource_ref
             FROM lnsat_authorization_nonces
             ORDER BY nonce_id",
        )
        .map_err(|_| SqliteStoreError::MigrationDrift)?;
    let identities = statement
        .query_map([], |row| {
            Ok((
                row.get::<_, String>(0)?,
                row.get::<_, String>(1)?,
                row.get::<_, String>(2)?,
            ))
        })
        .map_err(|_| SqliteStoreError::MigrationDrift)?
        .collect::<Result<Vec<_>, _>>()
        .map_err(|_| SqliteStoreError::MigrationDrift)?;
    let mut validated_state_event_count = 0_i64;
    for (nonce_id, project_ref, resource_ref) in identities {
        let stored = select_nonce_by_id(connection, &project_ref, &resource_ref, &nonce_id)
            .map_err(|_| SqliteStoreError::MigrationDrift)?
            .ok_or(SqliteStoreError::MigrationDrift)?;
        validated_state_event_count +=
            i64::try_from(stored.events.len()).map_err(|_| SqliteStoreError::MigrationDrift)?;
        validate_stored_nonce(connection, stored).map_err(|_| SqliteStoreError::MigrationDrift)?;
    }
    if validated_state_event_count != state_event_count {
        return Err(SqliteStoreError::MigrationDrift);
    }
    Ok(())
}

fn validate_issue_input(
    input: &Phase7AuthorizationNonceIssueInputV1<'_>,
) -> Result<(), Phase7PersistenceErrorV1> {
    if !bounded_reference(input.project_ref)
        || !is_valid_reference_v1(input.project_ref)
        || !bounded_reference(input.resource_ref)
        || !is_valid_reference_v1(input.resource_ref)
        || !valid_prefixed_id(input.authorization_attempt_id, "aat_")
    {
        return Err(Phase7PersistenceErrorV1::InvalidInput);
    }
    Ok(())
}

fn validate_nonce_scope(
    project_ref: &str,
    resource_ref: &str,
    nonce_id: &str,
) -> Result<(), Phase7PersistenceErrorV1> {
    if !bounded_reference(project_ref)
        || !is_valid_reference_v1(project_ref)
        || !bounded_reference(resource_ref)
        || !is_valid_reference_v1(resource_ref)
        || !valid_prefixed_id(nonce_id, "non_")
    {
        return Err(Phase7PersistenceErrorV1::InvalidInput);
    }
    Ok(())
}

fn validate_ttl_window(
    issued_at: &str,
    ttl_expires_at: &str,
) -> Result<(), Phase7PersistenceErrorV1> {
    let issued = canonical_utc_timestamp_millis_v1(issued_at)
        .ok_or(Phase7PersistenceErrorV1::ClockRejected)?;
    let expires = canonical_utc_timestamp_millis_v1(ttl_expires_at)
        .ok_or(Phase7PersistenceErrorV1::ClockRejected)?;
    if expires.checked_sub(issued) != Some(PHASE7_NONCE_TTL_MILLIS_V1) {
        return Err(Phase7PersistenceErrorV1::ClockRejected);
    }
    Ok(())
}

fn select_nonce_by_attempt(
    connection: &Connection,
    project_ref: &str,
    resource_ref: &str,
    attempt_id: &str,
) -> Result<Option<StoredNonce>, Phase7PersistenceErrorV1> {
    select_stored_nonce(
        connection,
        "nonce.project_ref = ?1
         AND nonce.resource_ref = ?2
         AND nonce.authorization_attempt_id = ?3",
        params![project_ref, resource_ref, attempt_id],
    )
}

fn select_nonce_by_id(
    connection: &Connection,
    project_ref: &str,
    resource_ref: &str,
    nonce_id: &str,
) -> Result<Option<StoredNonce>, Phase7PersistenceErrorV1> {
    select_stored_nonce(
        connection,
        "nonce.project_ref = ?1
         AND nonce.resource_ref = ?2
         AND nonce.nonce_id = ?3",
        params![project_ref, resource_ref, nonce_id],
    )
}

fn select_stored_nonce<P: rusqlite::Params>(
    connection: &Connection,
    predicate: &str,
    parameters: P,
) -> Result<Option<StoredNonce>, Phase7PersistenceErrorV1> {
    let sql = format!(
        "SELECT nonce.nonce_id,
                entity.audit_binding_id,
                nonce.project_ref,
                nonce.resource_ref,
                nonce.authorization_attempt_id,
                nonce.binding_digest,
                nonce.nonce_digest,
                nonce.issued_at,
                nonce.expires_at,
                entity.record_digest,
                entity.created_at,
                audit.event_kind,
                audit.authority_effect,
                audit.recorded_at
         FROM lnsat_authorization_nonces AS nonce
         JOIN lnsat_phase7_entities AS entity
           ON entity.entity_id = nonce.nonce_id
          AND entity.entity_kind = nonce.entity_kind
          AND entity.project_ref = nonce.project_ref
          AND entity.resource_ref = nonce.resource_ref
         JOIN lnsat_phase7_audit_bindings AS audit
           ON audit.audit_binding_id = entity.audit_binding_id
          AND audit.record_id = entity.entity_id
          AND audit.record_family = entity.entity_kind
          AND audit.project_ref = entity.project_ref
          AND audit.resource_ref = entity.resource_ref
          AND audit.record_digest = entity.record_digest
         WHERE {predicate}"
    );
    let base = connection
        .query_row(&sql, parameters, |row| {
            Ok(StoredNonce {
                nonce_id: row.get(0)?,
                audit_binding_id: row.get(1)?,
                project_ref: row.get(2)?,
                resource_ref: row.get(3)?,
                authorization_attempt_id: row.get(4)?,
                binding_digest: blob_32(row.get(5)?)?,
                nonce_digest: blob_32(row.get(6)?)?,
                issued_at: row.get(7)?,
                expires_at: row.get(8)?,
                stored_record_digest: blob_32(row.get(9)?)?,
                entity_created_at: row.get(10)?,
                audit_event_kind: row.get(11)?,
                audit_authority_effect: row.get(12)?,
                audit_recorded_at: row.get(13)?,
                events: Vec::new(),
            })
        })
        .optional()
        .map_err(|_| Phase7PersistenceErrorV1::PersistenceFailed)?;
    let Some(mut nonce) = base else {
        return Ok(None);
    };
    nonce.events = select_nonce_state_events(connection, &nonce.nonce_id)?;
    Ok(Some(nonce))
}

fn select_nonce_state_events(
    connection: &Connection,
    nonce_id: &str,
) -> Result<Vec<StoredNonceStateEvent>, Phase7PersistenceErrorV1> {
    let mut statement = connection
        .prepare(
            "SELECT event.state_event_id,
                    entity.audit_binding_id,
                    event.project_ref,
                    event.resource_ref,
                    event.target_entity_id,
                    event.target_entity_kind,
                    event.state_sequence,
                    event.state,
                    event.prior_state_event_id,
                    event.prior_state_sequence,
                    event.effective_at,
                    event.state_digest,
                    entity.record_digest,
                    entity.created_at,
                    audit.event_kind,
                    audit.authority_effect,
                    audit.recorded_at
             FROM lnsat_phase7_state_events AS event
             JOIN lnsat_phase7_entities AS entity
               ON entity.entity_id = event.state_event_id
              AND entity.entity_kind = event.entity_kind
              AND entity.project_ref = event.project_ref
              AND entity.resource_ref = event.resource_ref
             JOIN lnsat_phase7_audit_bindings AS audit
               ON audit.audit_binding_id = entity.audit_binding_id
              AND audit.record_id = entity.entity_id
              AND audit.record_family = entity.entity_kind
              AND audit.project_ref = entity.project_ref
              AND audit.resource_ref = entity.resource_ref
              AND audit.record_digest = entity.record_digest
             WHERE event.target_entity_id = ?1
             ORDER BY event.state_sequence",
        )
        .map_err(|_| Phase7PersistenceErrorV1::PersistenceFailed)?;
    statement
        .query_map([nonce_id], |row| {
            Ok(StoredNonceStateEvent {
                state_event_id: row.get(0)?,
                audit_binding_id: row.get(1)?,
                project_ref: row.get(2)?,
                resource_ref: row.get(3)?,
                target_entity_id: row.get(4)?,
                target_entity_kind: row.get(5)?,
                state_sequence: row.get(6)?,
                state: row.get(7)?,
                prior_state_event_id: row.get(8)?,
                prior_state_sequence: row.get(9)?,
                effective_at: row.get(10)?,
                state_digest: blob_32(row.get(11)?)?,
                stored_record_digest: blob_32(row.get(12)?)?,
                entity_created_at: row.get(13)?,
                audit_event_kind: row.get(14)?,
                audit_authority_effect: row.get(15)?,
                audit_recorded_at: row.get(16)?,
            })
        })
        .map_err(|_| Phase7PersistenceErrorV1::PersistenceFailed)?
        .collect::<Result<Vec<_>, _>>()
        .map_err(|_| Phase7PersistenceErrorV1::PersistenceFailed)
}

fn validate_stored_nonce(
    connection: &Connection,
    nonce: StoredNonce,
) -> Result<StoredNonce, Phase7PersistenceErrorV1> {
    validate_nonce_scope(&nonce.project_ref, &nonce.resource_ref, &nonce.nonce_id)
        .map_err(|_| Phase7PersistenceErrorV1::EvidenceDrift)?;
    if !valid_prefixed_id(&nonce.audit_binding_id, "p7a_")
        || !valid_prefixed_id(&nonce.authorization_attempt_id, "aat_")
        || nonce.entity_created_at != nonce.issued_at
        || nonce.audit_event_kind != "nonce_state_recorded"
        || nonce.audit_authority_effect != "none"
        || nonce.audit_recorded_at != nonce.issued_at
        || nonce.audit_binding_id
            != identifier("p7a_", NONCE_AUDIT_ID_DOMAIN, &[nonce.nonce_id.as_bytes()])
        || nonce_record_digest(&nonce) != nonce.stored_record_digest
    {
        return Err(Phase7PersistenceErrorV1::EvidenceDrift);
    }
    let attempt = read_validated_attempt_by_id(
        connection,
        &nonce.project_ref,
        &nonce.resource_ref,
        &nonce.authorization_attempt_id,
    )?
    .ok_or(Phase7PersistenceErrorV1::EvidenceDrift)?;
    validate_nonce_window(&nonce, &attempt)?;
    let expected_nonce_id = identifier("non_", NONCE_ID_DOMAIN, &[nonce.nonce_digest.as_slice()]);
    if nonce.nonce_id != expected_nonce_id || nonce.binding_digest != attempt.binding_digest {
        return Err(Phase7PersistenceErrorV1::EvidenceDrift);
    }
    validate_nonce_events(&nonce)?;
    Ok(nonce)
}

pub(super) fn read_validated_nonce_by_id(
    connection: &Connection,
    project_ref: &str,
    resource_ref: &str,
    nonce_id: &str,
) -> Result<Option<Phase7AuthorizationNonceRecordV1>, Phase7PersistenceErrorV1> {
    let validated = select_nonce_by_id(connection, project_ref, resource_ref, nonce_id)?
        .map(|stored| validate_stored_nonce(connection, stored))
        .transpose()?;
    validated
        .map(|nonce| {
            let issued_at = nonce.issued_at.clone();
            nonce_public_record(&nonce, &issued_at)
        })
        .transpose()
}

fn validate_nonce_window(
    nonce: &StoredNonce,
    attempt: &Phase7AuthorizationAttemptRecordV1,
) -> Result<(), Phase7PersistenceErrorV1> {
    let issued = canonical_utc_timestamp_millis_v1(&nonce.issued_at)
        .ok_or(Phase7PersistenceErrorV1::EvidenceDrift)?;
    let expires = canonical_utc_timestamp_millis_v1(&nonce.expires_at)
        .ok_or(Phase7PersistenceErrorV1::EvidenceDrift)?;
    let requested = canonical_utc_timestamp_millis_v1(&attempt.requested_at)
        .ok_or(Phase7PersistenceErrorV1::EvidenceDrift)?;
    let attempt_expires = canonical_utc_timestamp_millis_v1(&attempt.expires_at)
        .ok_or(Phase7PersistenceErrorV1::EvidenceDrift)?;
    let hard_cap = issued
        .checked_add(PHASE7_NONCE_TTL_MILLIS_V1)
        .ok_or(Phase7PersistenceErrorV1::EvidenceDrift)?;
    if issued < requested
        || issued >= attempt_expires
        || expires != hard_cap.min(attempt_expires)
        || expires <= issued
    {
        return Err(Phase7PersistenceErrorV1::EvidenceDrift);
    }
    Ok(())
}

fn validate_nonce_events(nonce: &StoredNonce) -> Result<(), Phase7PersistenceErrorV1> {
    if !(nonce.events.len() == 1 || nonce.events.len() == 2) {
        return Err(Phase7PersistenceErrorV1::EvidenceDrift);
    }
    let first = &nonce.events[0];
    if first.state != "active"
        || first.state_sequence != 1
        || first.prior_state_event_id.is_some()
        || first.prior_state_sequence.is_some()
        || first.effective_at != nonce.issued_at
    {
        return Err(Phase7PersistenceErrorV1::EvidenceDrift);
    }
    validate_nonce_event(nonce, first)?;
    if let Some(terminal) = nonce.events.get(1) {
        let terminal_millis = canonical_utc_timestamp_millis_v1(&terminal.effective_at)
            .ok_or(Phase7PersistenceErrorV1::EvidenceDrift)?;
        let issued_millis = canonical_utc_timestamp_millis_v1(&nonce.issued_at)
            .ok_or(Phase7PersistenceErrorV1::EvidenceDrift)?;
        let expires_millis = canonical_utc_timestamp_millis_v1(&nonce.expires_at)
            .ok_or(Phase7PersistenceErrorV1::EvidenceDrift)?;
        if terminal.state_sequence != 2
            || terminal.prior_state_event_id.as_deref() != Some(first.state_event_id.as_str())
            || terminal.prior_state_sequence != Some(1)
            || !matches!(terminal.state.as_str(), "cancelled" | "expired")
            || terminal_millis < issued_millis
            || (terminal.state == "cancelled" && terminal_millis >= expires_millis)
            || (terminal.state == "expired" && terminal.effective_at != nonce.expires_at)
        {
            return Err(Phase7PersistenceErrorV1::EvidenceDrift);
        }
        validate_nonce_event(nonce, terminal)?;
    }
    Ok(())
}

fn validate_nonce_event(
    nonce: &StoredNonce,
    event: &StoredNonceStateEvent,
) -> Result<(), Phase7PersistenceErrorV1> {
    let expected_event_id = nonce_state_event_id(nonce, &event.state, event.state_sequence);
    let expected_audit_id = identifier(
        "p7a_",
        NONCE_STATE_AUDIT_ID_DOMAIN,
        &[expected_event_id.as_bytes()],
    );
    let expected_effect = if event.state == "active" {
        "nonce_active"
    } else {
        "none"
    };
    if event.state_event_id != expected_event_id
        || event.audit_binding_id != expected_audit_id
        || event.project_ref != nonce.project_ref
        || event.resource_ref != nonce.resource_ref
        || event.target_entity_id != nonce.nonce_id
        || event.target_entity_kind != "authorization_nonce"
        || event.entity_created_at != event.effective_at
        || event.audit_event_kind != "nonce_state_recorded"
        || event.audit_authority_effect != expected_effect
        || event.audit_recorded_at != event.effective_at
        || nonce_state_digest(nonce, event) != event.state_digest
        || nonce_state_record_digest(event) != event.stored_record_digest
    {
        return Err(Phase7PersistenceErrorV1::EvidenceDrift);
    }
    Ok(())
}

fn materialize_expiry_if_needed(
    transaction: &Transaction<'_>,
    nonce: StoredNonce,
    checked_at: &str,
) -> Result<(StoredNonce, bool), Phase7PersistenceErrorV1> {
    let checked = canonical_utc_timestamp_millis_v1(checked_at)
        .ok_or(Phase7PersistenceErrorV1::ClockRejected)?;
    let issued = canonical_utc_timestamp_millis_v1(&nonce.issued_at)
        .ok_or(Phase7PersistenceErrorV1::EvidenceDrift)?;
    let latest = nonce
        .events
        .last()
        .ok_or(Phase7PersistenceErrorV1::EvidenceDrift)?;
    let latest_time = canonical_utc_timestamp_millis_v1(&latest.effective_at)
        .ok_or(Phase7PersistenceErrorV1::EvidenceDrift)?;
    if checked < issued || checked < latest_time {
        return Err(Phase7PersistenceErrorV1::ClockRejected);
    }
    let expires = canonical_utc_timestamp_millis_v1(&nonce.expires_at)
        .ok_or(Phase7PersistenceErrorV1::EvidenceDrift)?;
    if latest.state != "active" || checked < expires {
        return Ok((nonce, false));
    }
    insert_nonce_state_event(
        transaction,
        &nonce,
        "expired",
        &nonce.expires_at,
        Some(latest),
    )?;
    let reloaded = select_nonce_by_id(
        transaction,
        &nonce.project_ref,
        &nonce.resource_ref,
        &nonce.nonce_id,
    )?
    .ok_or(Phase7PersistenceErrorV1::EvidenceDrift)?;
    Ok((validate_stored_nonce(transaction, reloaded)?, true))
}

fn nonce_public_record(
    nonce: &StoredNonce,
    checked_at: &str,
) -> Result<Phase7AuthorizationNonceRecordV1, Phase7PersistenceErrorV1> {
    let checked = canonical_utc_timestamp_millis_v1(checked_at)
        .ok_or(Phase7PersistenceErrorV1::ClockRejected)?;
    let expires = canonical_utc_timestamp_millis_v1(&nonce.expires_at)
        .ok_or(Phase7PersistenceErrorV1::EvidenceDrift)?;
    let latest = nonce
        .events
        .last()
        .ok_or(Phase7PersistenceErrorV1::EvidenceDrift)?;
    let state_sequence = u32::try_from(latest.state_sequence)
        .map_err(|_| Phase7PersistenceErrorV1::EvidenceDrift)?;
    Ok(Phase7AuthorizationNonceRecordV1 {
        nonce_id: nonce.nonce_id.clone(),
        audit_binding_id: nonce.audit_binding_id.clone(),
        project_ref: nonce.project_ref.clone(),
        resource_ref: nonce.resource_ref.clone(),
        authorization_attempt_id: nonce.authorization_attempt_id.clone(),
        binding_digest: nonce.binding_digest,
        nonce_digest: nonce.nonce_digest,
        issued_at: nonce.issued_at.clone(),
        expires_at: nonce.expires_at.clone(),
        state_event_id: latest.state_event_id.clone(),
        state_audit_binding_id: latest.audit_binding_id.clone(),
        state_sequence,
        state: latest.state.clone(),
        state_effective_at: latest.effective_at.clone(),
        active: latest.state == "active" && checked < expires,
    })
}

fn insert_nonce_state_event(
    transaction: &Transaction<'_>,
    nonce: &StoredNonce,
    state: &str,
    effective_at: &str,
    prior: Option<&StoredNonceStateEvent>,
) -> Result<(), Phase7PersistenceErrorV1> {
    let state_sequence = prior.map_or(1, |event| event.state_sequence + 1);
    let state_event_id = nonce_state_event_id(nonce, state, state_sequence);
    let audit_binding_id = identifier(
        "p7a_",
        NONCE_STATE_AUDIT_ID_DOMAIN,
        &[state_event_id.as_bytes()],
    );
    if phase7_entity_exists(transaction, &state_event_id)?
        || audit_binding_exists(transaction, &audit_binding_id)?
    {
        return Err(Phase7PersistenceErrorV1::IdentityConflict);
    }
    let mut event = StoredNonceStateEvent {
        state_event_id,
        audit_binding_id,
        project_ref: nonce.project_ref.clone(),
        resource_ref: nonce.resource_ref.clone(),
        target_entity_id: nonce.nonce_id.clone(),
        target_entity_kind: "authorization_nonce".to_owned(),
        state_sequence,
        state: state.to_owned(),
        prior_state_event_id: prior.map(|event| event.state_event_id.clone()),
        prior_state_sequence: prior.map(|event| event.state_sequence),
        effective_at: effective_at.to_owned(),
        state_digest: [0; 32],
        stored_record_digest: [0; 32],
        entity_created_at: effective_at.to_owned(),
        audit_event_kind: "nonce_state_recorded".to_owned(),
        audit_authority_effect: if state == "active" {
            "nonce_active".to_owned()
        } else {
            "none".to_owned()
        },
        audit_recorded_at: effective_at.to_owned(),
    };
    event.state_digest = nonce_state_digest(nonce, &event);
    event.stored_record_digest = nonce_state_record_digest(&event);
    insert_entity_and_audit(
        transaction,
        &event.state_event_id,
        "phase7_state_event",
        &event.project_ref,
        &event.resource_ref,
        &event.audit_binding_id,
        &event.stored_record_digest,
        "nonce_state_recorded",
        &event.audit_authority_effect,
        &event.effective_at,
    )?;
    transaction
        .execute(
            "INSERT INTO lnsat_phase7_state_events (
                state_event_id, entity_kind, project_ref, resource_ref,
                target_entity_id, target_entity_kind, state_sequence, state,
                prior_state_event_id, prior_state_sequence, effective_at,
                state_digest
             ) VALUES (
                ?1, 'phase7_state_event', ?2, ?3, ?4,
                'authorization_nonce', ?5, ?6, ?7, ?8, ?9, ?10
             )",
            params![
                &event.state_event_id,
                &event.project_ref,
                &event.resource_ref,
                &event.target_entity_id,
                event.state_sequence,
                &event.state,
                &event.prior_state_event_id,
                event.prior_state_sequence,
                &event.effective_at,
                event.state_digest.as_slice(),
            ],
        )
        .map_err(|_| Phase7PersistenceErrorV1::PersistenceFailed)?;
    Ok(())
}

#[allow(clippy::too_many_arguments)]
pub(super) fn insert_entity_and_audit(
    transaction: &Transaction<'_>,
    entity_id: &str,
    entity_kind: &str,
    project_ref: &str,
    resource_ref: &str,
    audit_binding_id: &str,
    record_digest: &[u8; 32],
    event_kind: &str,
    authority_effect: &str,
    recorded_at: &str,
) -> Result<(), Phase7PersistenceErrorV1> {
    transaction
        .execute(
            "INSERT INTO lnsat_phase7_entities (
                entity_id, entity_kind, project_ref, resource_ref,
                audit_binding_id, record_digest, created_at
             ) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)",
            params![
                entity_id,
                entity_kind,
                project_ref,
                resource_ref,
                audit_binding_id,
                record_digest.as_slice(),
                recorded_at,
            ],
        )
        .map_err(|_| Phase7PersistenceErrorV1::PersistenceFailed)?;
    transaction
        .execute(
            "INSERT INTO lnsat_phase7_audit_bindings (
                audit_binding_id, record_id, record_family, project_ref,
                resource_ref, record_digest, event_kind, authority_effect,
                recorded_at
             ) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)",
            params![
                audit_binding_id,
                entity_id,
                entity_kind,
                project_ref,
                resource_ref,
                record_digest.as_slice(),
                event_kind,
                authority_effect,
                recorded_at,
            ],
        )
        .map_err(|_| Phase7PersistenceErrorV1::PersistenceFailed)?;
    Ok(())
}

fn nonce_digest_exists(
    connection: &Connection,
    project_ref: &str,
    nonce_digest: &[u8; 32],
) -> Result<bool, Phase7PersistenceErrorV1> {
    connection
        .query_row(
            "SELECT 1 FROM lnsat_authorization_nonces
             WHERE project_ref = ?1 AND nonce_digest = ?2",
            params![project_ref, nonce_digest.as_slice()],
            |_| Ok(()),
        )
        .optional()
        .map(|value| value.is_some())
        .map_err(|_| Phase7PersistenceErrorV1::PersistenceFailed)
}

fn nonce_record_digest(nonce: &StoredNonce) -> [u8; 32] {
    digest_fields(
        NONCE_RECORD_DIGEST_DOMAIN,
        &[
            nonce.nonce_id.as_bytes(),
            nonce.audit_binding_id.as_bytes(),
            nonce.project_ref.as_bytes(),
            nonce.resource_ref.as_bytes(),
            nonce.authorization_attempt_id.as_bytes(),
            &nonce.binding_digest,
            &nonce.nonce_digest,
            nonce.issued_at.as_bytes(),
            nonce.expires_at.as_bytes(),
        ],
    )
}

fn nonce_state_event_id(nonce: &StoredNonce, state: &str, state_sequence: i64) -> String {
    let sequence = state_sequence.to_be_bytes();
    identifier(
        "ste_",
        NONCE_STATE_EVENT_ID_DOMAIN,
        &[nonce.nonce_id.as_bytes(), state.as_bytes(), &sequence],
    )
}

fn nonce_state_digest(nonce: &StoredNonce, event: &StoredNonceStateEvent) -> [u8; 32] {
    let sequence = event.state_sequence.to_be_bytes();
    let prior_sequence = event.prior_state_sequence.unwrap_or(0).to_be_bytes();
    digest_fields(
        NONCE_STATE_DIGEST_DOMAIN,
        &[
            nonce.nonce_id.as_bytes(),
            &nonce.binding_digest,
            &nonce.nonce_digest,
            event.state.as_bytes(),
            &sequence,
            event
                .prior_state_event_id
                .as_deref()
                .unwrap_or("")
                .as_bytes(),
            &prior_sequence,
            event.effective_at.as_bytes(),
        ],
    )
}

fn nonce_state_record_digest(event: &StoredNonceStateEvent) -> [u8; 32] {
    let sequence = event.state_sequence.to_be_bytes();
    digest_fields(
        NONCE_STATE_RECORD_DIGEST_DOMAIN,
        &[
            event.state_event_id.as_bytes(),
            event.audit_binding_id.as_bytes(),
            event.project_ref.as_bytes(),
            event.resource_ref.as_bytes(),
            event.target_entity_id.as_bytes(),
            event.target_entity_kind.as_bytes(),
            &sequence,
            event.state.as_bytes(),
            &event.state_digest,
            event.effective_at.as_bytes(),
        ],
    )
}

fn identifier(prefix: &str, domain: &str, fields: &[&[u8]]) -> String {
    let digest = digest_fields(domain, fields);
    let mut encoded = String::with_capacity(prefix.len() + 64);
    encoded.push_str(prefix);
    for byte in digest {
        encoded.push(char::from(LOWER_HEX[usize::from(byte >> 4)]));
        encoded.push(char::from(LOWER_HEX[usize::from(byte & 0x0f)]));
    }
    encoded
}

pub(super) fn canonical_system_time_v1(
    value: SystemTime,
) -> Result<String, Phase7PersistenceErrorV1> {
    let duration = value
        .duration_since(UNIX_EPOCH)
        .map_err(|_| Phase7PersistenceErrorV1::ClockRejected)?;
    let total_millis =
        u64::try_from(duration.as_millis()).map_err(|_| Phase7PersistenceErrorV1::ClockRejected)?;
    let total_seconds = total_millis / 1_000;
    let millisecond = total_millis % 1_000;
    let days = total_seconds / 86_400;
    let seconds_of_day = total_seconds % 86_400;
    let hour = seconds_of_day / 3_600;
    let minute = (seconds_of_day % 3_600) / 60;
    let second = seconds_of_day % 60;
    let (year, month, day) =
        civil_date_from_unix_days_v1(days).ok_or(Phase7PersistenceErrorV1::ClockRejected)?;
    if year > 9_999 {
        return Err(Phase7PersistenceErrorV1::ClockRejected);
    }
    let canonical = format!(
        "{year:04}-{month:02}-{day:02}T{hour:02}:{minute:02}:{second:02}.{millisecond:03}Z"
    );
    canonical_utc_timestamp_millis_v1(&canonical)
        .map(|_| canonical)
        .ok_or(Phase7PersistenceErrorV1::ClockRejected)
}

fn civil_date_from_unix_days_v1(days: u64) -> Option<(u64, u64, u64)> {
    let shifted = i64::try_from(days).ok()?.checked_add(719_468)?;
    let era = shifted / 146_097;
    let day_of_era = shifted - era * 146_097;
    let year_of_era =
        (day_of_era - day_of_era / 1_460 + day_of_era / 36_524 - day_of_era / 146_096) / 365;
    let mut year = year_of_era + era * 400;
    let day_of_year = day_of_era - (365 * year_of_era + year_of_era / 4 - year_of_era / 100);
    let month_prime = (5 * day_of_year + 2) / 153;
    let day = day_of_year - (153 * month_prime + 2) / 5 + 1;
    let month = month_prime + if month_prime < 10 { 3 } else { -9 };
    year += i64::from(month <= 2);
    Some((
        u64::try_from(year).ok()?,
        u64::try_from(month).ok()?,
        u64::try_from(day).ok()?,
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn trusted_system_clock_formats_canonical_utc_and_rejects_pre_epoch() {
        assert_eq!(
            canonical_system_time_v1(UNIX_EPOCH),
            Ok("1970-01-01T00:00:00.000Z".to_owned())
        );
        let leap_day = UNIX_EPOCH
            .checked_add(Duration::from_secs(951_827_696))
            .and_then(|value| value.checked_add(Duration::from_millis(789)))
            .expect("known leap-day timestamp must fit");
        assert_eq!(
            canonical_system_time_v1(leap_day),
            Ok("2000-02-29T12:34:56.789Z".to_owned())
        );
        assert_eq!(
            canonical_system_time_v1(
                UNIX_EPOCH
                    .checked_sub(Duration::from_millis(1))
                    .expect("pre-epoch timestamp must construct")
            ),
            Err(Phase7PersistenceErrorV1::ClockRejected)
        );
    }
}
